title: PT. DHIYA ANEKA TEKNIK
url: "http://k3.dhiya.id"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname: dhiya.id

# Default description in social shares for the jekyll-seo-tag gem
description: Your Partner in Safety.

# Author details for the jekyll-seo-tag gem
author:
  name:
  email:
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: PT. DHIYA ANEKA TEKNIK
  links:
    - http://k3.dhiya.id

collections:
  staffs:
    output: true
  albums:
    output: true

paginate: 5
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "staffs"
    values:
      layout: "staff"
      _options:
        image_path:
          width: 512
          height: 512
  - scope:
      path: ""
      type: "albums"
    values:
      layout: "album"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
